services:
  gateway:
    image: docker/mcp-gateway
    ports:
      - "8811:8811"
    volumes:
      - ${HOME}/.docker/mcp:/mcp:ro
      - /var/run/docker.sock:/var/run/docker.sock
    command:
      - --transport=streaming
      # - --servers=duckduckgo,fetch
      - --port=8811
      # - --catalog=/mcp/catalogs/docker-mcp.yaml 
      - --config=/mcp/config.yaml
      - --registry=/mcp/registry.yaml
      - --tools-config=/mcp/tools.yaml
      - --transport=sse
      
