[python-dev]
image="quay.io/toolbx-images/ubuntu-toolbox:22.04"
additional_packages="curl openssh-client gpg make build-essential libssl-dev zlib1g-dev libbz2-dev libreadline-dev libsqlite3-dev llvm libncursesw5-dev xz-utils tk-dev libxml2-dev libxmlsec1-dev libffi-dev liblzma-dev fonts-noto-color-emoji"
home="${home_dir}/distrobox/python-dev"
init_hooks=sudo ln -sf /usr/bin/distrobox-host-exec /usr/local/bin/docker;
# init_hooks=sudo -u bob git config --global user.name 'mrllama123';
# init_hooks=sudo -u bob git config --global user.email 'piesrule123@gmail.com';
# #init_hooks=sudo -u ${user} ssh-add ${ssh_key}
# init_hooks=sudo -u ${user} git clone https://github.com/asdf-vm/asdf.git ${home_dir}/distrobox/python-dev/.asdf --branch v0.13.1;
# init_hooks=sudo -u ${user} curl https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh | sudo -u bob bash -s  -- 'unattended';
#init_hooks=sudo -u ${user} cat ${script_dir}/.zshrc > ${home_dir}/distrobox/python-dev/.zshrc;
init_hooks=sudo -u ${user} cp ${script_dir}/post-setup.sh ${home_dir}/distrobox/python-dev/post-setup.sh;
init_hooks=sudo -u ${user} chmod +x ${home_dir}/distrobox/python-dev/post-setup.sh;
init_hooks=sudo -u ${user} cp ${script_dir}/.zshrc.devbox ${home_dir}/distrobox/python-dev/.zshrc.devbox;
init_hooks=sudo -u ${user} ${home_dir}/distrobox/python-dev/post-setup.sh;
pull=true
replace=true
